# Example markdownlint configuration with all properties set to their default value

# Default state for all rules
default: true

# disable line length rules: Markdown files will be wrapped by the viewer.
MD013: false
