---
# Copyright (c) 2026 sharm294
# SPDX-License-Identifier: AGPL-3.0-or-later

version: "0.2"
ignorePaths: [cspell.config.yaml]
language: en
dictionaryDefinitions: []
dictionaries: [en_US, softwareTerms]
words:
  - adfiles
  - appledouble
  - ashift
  - backrefs
  - bootable
  - bootdisk
  - bpve
  - cdrom
  - changeme
  - chrony
  - cicustom
  - cipassword
  - ciuser
  - cloudimage
  - cloudinit
  - codespell
  - corosync
  - cramfs
  - dmypy
  - EDITMSG
  - efidisk
  - efitype
  - endfor
  - envrc
  - firewire
  - freevxfs
  - genericcloud
  - hfsplus
  - htmlcov
  - importdisk
  - iothread
  - iscsi
  - isolinux
  - iucode
  - jffs
  - journalctl
  - keyrings
  - kwargs
  - lineinfile
  - listfile
  - lvmthin
  - metas
  - mkpasswd
  - mypy
  - netif
  - netinst
  - nologin
  - nullglob
  - ostemplate
  - ostype
  - ovmf
  - partitioner
  - pdbedit
  - pipefail
  - preconfiguration
  - preseed
  - preseeded
  - proxmoxlib
  - pveam
  - pvesm
  - pvetest
  - pveversion
  - pycache
  - pyenv
  - pyinfra
  - pypirc
  - pytest
  - PyYAML
  - qcow
  - resolv
  - rfork
  - rootdir
  - rootfs
  - runcmd
  - scsihw
  - sdist
  - seabios
  - sharm
  - Sharma
  - shellcheck
  - sshkeys
  - thinpool
  - trixie
  - UEFI
  - urandom
  - Varun
  - varunsh
  - venv
  - vgname
  - virtio
  - vmbr
  - vmid
  - vztmpl
  - wipefs
  - writethrough
  - xattr
  - yourpassword
  - zfspool
ignoreWords: []
import: []
languageSettings:
  - languageId: shellscript
    locale: "*"
    dictionaries: [bash]
    ignoreRegExpList:
      - -\w+
    words:
      - adfiles
      - appledouble
      - corosync
      - iucode
      - listfile
      - nologin
      - nullglob
      - proxmoxlib
      - pveam
      - rfork
      - vztmpl
      - xattr
      - yourpassword
      - zfspool
  - languageId: python
    locale: "*"
    dictionaries: [python]
  - languageId: c,cpp
    locale: "*"
    dictionaries: [cpp]
  - languageId: properties
    locale: "*"
    dictionaries: [cpp]
    words:
      - ALSA
      - autoconfig
      - bootdev
      - cdrom
      - chsh
      - crypted
      - debconf
      - debootstrap
      - espeak
      - espeakup
      - iflabel
      - inittab
      - keybox
      - localechooser
      - multiarch
      - multiraid
      - netcfg
      - netinst
      - nousb
      - partman
      - pkgsel
      - preseed
      - preseeded
      - preseeding
      - reusemethod
      - tasksel
      - udeb
