# Copyright (c) 2026 sharm294
# SPDX-License-Identifier: AGPL-3.0-or-later

---
galaxy_info:
  author: sharm294
  description: Simple role to install and configure Samba shares used by the project
  company: ""
  license: AGPL-3.0-or-later
  min_ansible_version: "2.9"
dependencies: []
